//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarteringAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_images
    {
        public int Image_id { get; set; }
        public string Image_01 { get; set; }
        public string Image_02 { get; set; }
        public string Image_03 { get; set; }
        public string Image_04 { get; set; }
        public string Image_05 { get; set; }
        public Nullable<int> Item_id { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
