//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarteringAppAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarteringAppEntities : DbContext
    {
        public BarteringAppEntities()
            : base("name=BarteringAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Item_images> Item_images { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Offered_items> Offered_items { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Trusted_party> Trusted_party { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Verification_requests> Verification_requests { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Attribute_Values> Attribute_Values { get; set; }
        public virtual DbSet<Subcategories> Subcategories { get; set; }
        public virtual DbSet<Subcategory_Attributes> Subcategory_Attributes { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<uploadedItemsAttributes> uploadedItemsAttributes { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<WishList> WishList { get; set; }
    }
}
