//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarteringAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int n_id { get; set; }
        public string message { get; set; }
        public Nullable<int> Item_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Status { get; set; }
    
        public virtual Item Items { get; set; }
        public virtual User Users { get; set; }
    }
}
