//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarteringAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Req_id { get; set; }
        public string Date { get; set; }
        public string Req_status { get; set; }
        public Nullable<int> Offer_id { get; set; }
        public string ConfirmOfferRequestSender { get; set; }
        public string ConfirmOfferRequestReceiver { get; set; }
    
        public virtual Offer Offer { get; set; }
    }
}
