//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarteringAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategory_Attributes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subcategory_Attributes()
        {
            this.Attribute_Values = new HashSet<Attribute_Values>();
        }
    
        public int attribute_id { get; set; }
        public string attribute_name { get; set; }
        public Nullable<int> subcategory_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attribute_Values> Attribute_Values { get; set; }
        public virtual Subcategories Subcategories { get; set; }
    }
}
