//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarteringAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verification_requests
    {
        public int Verification_id { get; set; }
        public Nullable<int> Trusted_party_id { get; set; }
        public Nullable<int> Item_id { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Trusted_party Trusted_party { get; set; }
    }
}
